alternate: mikunの部屋 # 站点大标题

# 实验性特性
experiments:
  debug: false # 使用debug模式启动
  disableThemeComment: false # 禁用主题评论系统(一般用于关闭评论或让插件接管评论系统)
  usingRelative: false # _image.yml 使用相对路径
  optimizeLongPosts: false # 优化长文章，这能让长文章的FPS提升70%-150%并解决假死问题，但存在一些副作用
  # 具体见https://docs.kaitaku.xyz/guide/theme.html#%E9%95%BF%E6%96%87%E7%AB%A0%E4%BC%98%E5%8C%96
  mobileWidth: 820px # 移动版和桌面版导航栏最短切换长度
  # 使用 Cloudflare Rocket 或其他优化功能时需开启下列补丁，否则主题无法渲染
  cloudflarePatch: false
  coverConfig:
    enableCover: true # 是否开启头图
    enablePreload: true #是否开启预加载头图
    enableNextGradientCover: false # 使用CSS渐变作为上/下一页封面
  copyrightLength: 50 # 自定义复制时显示copyright的长度
  antiFakeWebsite: true # 防止恶意网站伪装


darkmode: true

loader:
  start: true # 进入页面时显示加载动画
  switch: false # 切换页面时显示加载动画

font:
  enable: true
  # 从google字体库加载,如果自定义@font-face请关闭
  loadFromGoogle: true
  # 字体选项:
  # `external`:从google字体库加载字体.
  # `family: 字体家族名,无需引号
  # `size: x.x`. 以`em`为单位. 默认: 1 (16px)

  # 适用于所有在body标签内的文字.
  global:
    external: true
    # https://fonts.google.com/specimen/Kiwi+Maru?lang=ja_Jpan
    family: Kiwi Maru
    size:

  # 大标题字体.
  logo:
    external: true
    # https://fonts.google.com/specimen/Hachi+Maru+Pop?lang=ja_Jpan
    family: Hachi Maru Pop
    size: 3.5

  # 页面标题字体.
  title:
    external: true
    family: Noto Serif JP
    size: 2.5

  # 标题字体.
  headings:
    external: true
    family: Noto Serif SC
    size:

  # 文章字体.
  posts:
    external: false
    family:

  # 代码块的字体
  codes:
    external: true
    family: Inconsolata


# Social Links
# Usage: `Key: permalink || icon || color`
# Key is the link label showing to end users.
# Value before `||` delimiter is the target permalink,
# secend value is the name of Font icon.
social:
  github: https://github.com/mikun12138 || github || "#191717"
  #gitee: https://gitee.com/yourname || gitee || "#e60026"
  #google: https://plus.google.com/yourname || google
  #twitter: https://twitter.com/yourname || twitter || "#00aff0"
  #zhihu: https://www.zhihu.com/people/yourname || zhihu || "#1e88e5"
  music: https://music.163.com/#/user/home?id=1533489887 || cloud-music || "#e60026"
  #weibo: https://weibo.com/yourname || weibo || "#ea716e"
  #about: https://about.me/yourname || address-card || "#3b5998"
  #email: mailto:foo@xxx.com || envelope || "#55acd5"
  #facebook: https://www.facebook.com/yourname || facebook
  #stackoverflow: https://stackoverflow.com/ || stack-overflow
  #youtube: https://youtube.com/yourname || youtube
  #instagram: https://instagram.com/yourname || instagram
  #skype: skype:yourname?call|chat || skype
  #douban: https://www.douban.com/people/yourname/ || douban

footer:
  # Specify the date when the site was set up. If not defined, current year will be used.
  since: 2022
  icon:
    name: sakura rotate
    # Change the color of icon, using Hex Code.
    color: "#ffc0cb"
  # Dependencies: https://github.com/theme-next/hexo-symbols-count-time
  count: true
  powered: true
  lantern:
    enable: true #是否开启
    word1: 中 #第一个字
    word2: 秋 #第二个字
  icp: # ICP备案
    enable: false
    # 请在登录后从 https://beian.mps.gov.cn/web/business/businessHome/website 下载对应图标
    icon: "" #网安备案图片
    icpnumber: "xxx" # ICP备案号
    beian: "xxx" # 网安备案号
    recordcode: "xxx" # 网安备案链接中的recordcode参数

post:
  count: false

reward:
  # If true, reward will be displayed in every article by default.
  enable: false
  account:
    wechatpay: /wechatpay.png
    alipay: /alipay.png
    # paypal: /paypal.png


# bgm 
# 不使用请打开noplayer功能
audio:
  - title: MVP
    list:
      - https://music.163.com/#/playlist?id=13791554505




# markdown:
#   render: # 渲染器设置
#     html: false # 过滤 HTML 标签
#     xhtmlOut: true # 使用 '/' 来闭合单标签 （比如 <br />）。
#     breaks: true # 转换段落里的 '\n' 到 <br>。
#     linkify: true # 将类似 URL 的文本自动转换为链接。
#     typographer:
#     quotes: "“”‘’"
#   plugins: # markdown-it 插件设置
#     - plugin:
#         name: markdown-it-toc-and-anchor
#         enable: true
#         options: # 文章目录以及锚点应用的 class 名称，shoka 系主题必须设置成这样
#           tocClassName: "toc"
#           anchorClassName: "anchor"
#     - plugin:
#         name: markdown-it-multimd-table
#         enable: true
#         options:
#           multiline: true
#           rowspan: true
#           headerless: true
#     - plugin:
#         name: ./markdown-it-furigana
#         enable: true
#         options:
#           fallbackParens: "()"
#     - plugin:
#         name: ./markdown-it-spoiler
#         enable: true
#         options:
#           title: "你知道得太多了"

# minify:
#   js:
#     enable: false # ShokaX 自带 esbuild 优化，不建议开启，其他主题建议开启
#     exclude: # 排除文件，接受 string[]，需符合 micromatch 格式
#   css:
#     enable: true # 开启 CSS 优化
#     options:
#       targets: ">= 0.5%" # browserslist 格式的 target
#     exclude: # 排除文件，接受 string[]，需符合 micromatch 格式
#   html:
#     minifier: html-minifier
#     enable: true # 开启 HTML 优化
#     options:
#       comments: false # 是否保留注释内容
#     exclude: # 排除文件，接受 string[]，需符合 micromatch 格式
#   image:
#     enable: false # 开启图片预处理和自动 WebP 化
#     options:
#       avif: false
#       webp: true # 预留配置项，现版本无作用
#       quality: 80 # 质量，支持1-100的整数、lossless或nearLossless
#       effort: 2 # CPU 工作量，0-6之间的整数(越低越快)
#       replaceSrc: false # 自动替换生成html中的本地图片链接为webp链接
#       # 对于使用 CI 工作流部署的用户，请注意本配置可能导致图片 404，如果出现请关闭
#       # 我们更建议使用 Service Worker 来在用户侧实现 replaceSrc 的功能，这将能够以一种侵入式更小的方式实现链接替换
#     exclude: